# Generated by Django 6.0.3 on 2026-08-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_mediaasset_md5'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='conservation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='labels',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='marque',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='nouveaute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='url_produit',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
