# Generated by Django 6.0.3 on 2026-09-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_mediaasset_firebase_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='ai_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='duplicate_group',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='duplicate_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='tags_validated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='tags_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='tags_validated_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='validation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('archive', 'Archive'), ('termine', 'Terminé')], default='en_cours', max_length=20),
        ),
    ]
