# Generated by Django 6.0.3 on 2026-09-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_mediaasset_ai_title_mediaasset_duplicate_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='ai_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='ai_confidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='ai_context',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='ai_embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='ai_logos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='ai_objects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='ai_ocr',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='ai_people',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='gold_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='gold_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='gold_feedback',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='gold_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='gold_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='media_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('AI_ANALYZING', 'AI analyzing'), ('AI_ANALYZED', 'AI analyzed'), ('ADMIN_REVIEW', 'Admin review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_CORRECTION', 'Needs correction'), ('ARCHIVED', 'Archived')], db_index=True, default='UPLOADED', max_length=30),
        ),
    ]
