# Generated by Django 6.0.3 on 2026-09-19 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_mediaasset_ai_analysis_mediaasset_ai_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TagCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.JSONField(default=list)),
                ('after', models.JSONField(default=list)),
                ('reference', models.CharField(blank=True, max_length=20)),
                ('author', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='portal.mediaasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
