# Generated by Django 6.0.3 on 2026-09-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_seed_tag_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='ai_colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='ai_concepts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='ai_places',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='ai_visual_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='search_embedding_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='search_embedding_model',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
