# Generated by Django 6.0.3 on 2026-09-20 08:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_mediaasset_ai_colors_mediaasset_ai_concepts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='color_signature',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='perceptual_hash',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='tagcorrection',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, default='PENDING', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_run', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_job', to='portal.mediaasset')),
            ],
        ),
        migrations.CreateModel(
            name='FirebaseOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=80)),
                ('document_id', models.CharField(max_length=180)),
                ('payload', models.JSONField(default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_run', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('collection', 'document_id'), name='unique_outbox_document')],
            },
        ),
        migrations.CreateModel(
            name='TagFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Ajouter'), ('remove', 'Retirer')], max_length=10)),
                ('tag', models.CharField(max_length=80)),
                ('reason', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_events', to='portal.mediaasset')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
